path: /home/wyh_home/MedicalYOLO/data
train: /home/wyh_home/MedicalYOLO/data/train/images
val: /home/wyh_home/MedicalYOLO/data/val/images
test: /home/wyh_home/MedicalYOLO/data/test/images
nc: 4
names: ['objects', 'glioma_tumor', 'meningioma_tumor', 'pituitary_tumor']
