# 数据集配置文件
# 请根据你的实际数据路径修改

# 数据路径
path: data  # 数据集根目录
train: train/images  # 训练图片路径
val: val/images      # 验证图片路径
test: test/images    # 测试图片路径（可选）

# 类别数量
nc: 1  # 请根据你的实际类别数量修改

# 类别名称
names:
  0: medical_object  # 请根据你的实际类别名称修改
